[phases.setup]
nixPkgs = ['nodejs-18_x', 'yarn']

[[services]]
name = "backend"
source = "server/"
build = "npm install"
start = "npm start"
targetPort = 5000

[[services]]
name = "frontend"
source = "client/"
build = "npm install && npm run build"
start = "npx serve -s build"
targetPort = 3000
